### ISSUE TITLE
CLI: Adding new service doesn't provision

### ISSUE THREAD

**Issue by DeviaVir** [pebble/flotilla#15]
`$ docker run -v /Users/chase/.aws/pebbledev.credentials:/root/.aws/credentials flotilla service --region us-east-1 --name docker-registry --elb-scheme internet-facing --dns-name registry-flotilla.pebbledev.com --health-check 10 --instance-type t2.small --provision --instance-min 1 --instance-max 2`

`2016-01-12 08:24:24,520 - INFO - MainThread - Service docker-registry updated in: us-east-1`

Tried to test roll out a service, after running `init`. Stacks table is empty, it is added to the services table but no service seems to get rolled out.

**Comment by thepwagner** [comment]
journalctl@scheduler says:
`Jan 12 10:13:15 ip-192-168-1-71.ec2.internal docker[953]: 2016-01-12 10:13:15,710 - provisioner-us-east-1 - No regions defined, nothing to provision.`

But that log entry was removed https://github.com/thepwagner/flotilla/commit/1dea3e50cd0fb87458187aed8419d81a623852ea ..


`systemctl restart flotilla` to pull the latest flotilla container:
```
Jan 12 10:16:38 ip-192-168-1-71.ec2.internal docker[7011]: 2016-01-12 10:16:38,641 - DEBUG - provisioner-us-east-1 - Stack flotilla-develop-vpc is CREATE_IN_PROGRESS
Jan 12 10:16:38 ip-192-168-1-71.ec2.internal docker[7011]: 2016-01-12 10:16:38,641 - DEBUG - provisioner-us-east-1 - Waiting on VPC in us-east-1 for: [u'docker-registry']
```

I should definitely improve SSH key handling so other people can login and grab logs (right now everything is backdoored for me only via cloud-config :/).

Now your problem is:
```
Jan 12 10:19:54 ip-192-168-1-71.ec2.internal docker[7011]: BotoServerError: BotoServerError: 400 Bad Request
Jan 12 10:19:54 ip-192-168-1-71.ec2.internal docker[7011]: {"Error":{"Code":"ValidationError","Message":"Parameter 'HealthCheckTarget' must match pattern (TCP|HTTP|HTTPS|SSL):(.*?)","Type":"Sender"},"RequestId":"05c47c05-b916-11e5-af95-831803dda72a"}
```


try:
`docker run -v /Users/chase/.aws/pebbledev.credentials:/root/.aws/credentials flotilla service --region us-east-1 --name docker-registry --health-check HTTP:80/` to recover (TODO: input validation :) )
